### ISSUE TITLE
In the case of a murderer leaving when there is only 1 innocent left, the innocent becomes a murderer with no one to kill.

### ISSUE THREAD

**Issue by MarkiusVI** [LeonardoTheMutant/SRB2-Murder-Mystery#4]
If there is 1 murderer and 1 innocent left with the Sheriff's emerald laying around, and the murderer leaves then the innocent is declared the murderer with no one to kill essentially softlocking the game.

**Comment by LeonardoTheMutant** [comment]
[b605780](https://github.com/LeonardoTheMutant/SRB2-Murder-Mystery/commit/b605780694beed252ef73cb1e56d806a96f540bc)
