### ISSUE TITLE
False information

### ISSUE THREAD

**Issue by tedbasher** [LeonardoTheMutant/SRB2-Murder-Mystery#6]
https://github.com/LeonardoTheMutant/SRB2-Murder-Mystery/blob/main/SRC/FOR_DEVELOPERS.txt
It specifies `DOCS` despite it being renamed to `MANUALS`

**Comment by tedbasher** [comment]
false its docs now??? I remember seeing a change to manuals my bad

**Comment by tedbasher** [comment]
wrong!
theres `docs` and `MANUALS`
i think this one means `MANUALS` so it's wrong

**Comment by LeonardoTheMutant** [comment]
Fixed in [2f2dcf6](https://github.com/LeonardoTheMutant/SRB2-Murder-Mystery/commit/2f2dcf60db88215e35c3c7a18b8f939d86eecd84)
