### ISSUE TITLE
Scalled down + looped (some) songs

### ISSUE THREAD

**Issue by Troplucky** [LeonardoTheMutant/SRB2-Murder-Mystery#7]
This is just some scalled down vers of all songs included in the digital ver of the ost, all ready for testing if you want to check.

The request is to use those and possible have them in the base pk3 thanks to the heavilly lowered file size
[ScalledDownSongs.zip](https://github.com/user-attachments/files/15972858/ScalledDownSongs.zip)

**Comment by LeonardoTheMutant** [comment]
This could be a "Push Request" instead but these songs might actually fit into the base package
